In [1]:
import tensorflow as tf
import numpy as np
from tensorflow import keras

In [2]:
# 1. 데이터 로드
max_features = 10000   # 사용할 단어 수
max_len = 200          # 문장 길이를 200으로 패딩

(x_train, y_train), (x_test, y_test) = keras.datasets.imdb.load_data(num_words=max_features)

# 시퀀스 패딩
x_train = keras.preprocessing.sequence.pad_sequences(x_train, maxlen=max_len)
x_test = keras.preprocessing.sequence.pad_sequences(x_test, maxlen=max_len)


In [5]:
model = keras.Sequential([
    keras.layers.Embedding(input_dim=max_features, output_dim=16, input_length=max_len),
    keras.layers.LSTM(4),
    keras.layers.Dense(1, activation='sigmoid')
])

In [6]:
model2 = keras.Sequential([
    keras.layers.Embedding(input_dim=max_features, output_dim=16, input_length=max_len),
    keras.layers.GlobalAveragePooling1D(),
    keras.layers.Dense(16, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])
model2.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 200, 16)           160000    
                                                                 
 global_average_pooling1d_1   (None, 16)               0         
 (GlobalAveragePooling1D)                                        
                                                                 
 dense_4 (Dense)             (None, 16)                272       
                                                                 
 dense_5 (Dense)             (None, 1)                 17        
                                                                 
Total params: 160,289
Trainable params: 160,289
Non-trainable params: 0
_________________________________________________________________


In [7]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 200, 16)           160000    
                                                                 
 lstm_1 (LSTM)               (None, 4)                 336       
                                                                 
 dense_3 (Dense)             (None, 1)                 5         
                                                                 
Total params: 160,341
Trainable params: 160,341
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [9]:
model2.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [10]:
history = model.fit(
    x_train, y_train,
    epochs=20,
    batch_size=64,
    validation_split=0.2
)

Epoch 1/20
313/313 [==============================] - 7s 12ms/step - loss: 0.5463 - accuracy: 0.7623 - val_loss: 0.4336 - val_accuracy: 0.8382
Epoch 2/20
313/313 [==============================] - 4s 11ms/step - loss: 0.3535 - accuracy: 0.8781 - val_loss: 0.3645 - val_accuracy: 0.8566
Epoch 3/20
313/313 [==============================] - 4s 12ms/step - loss: 0.2756 - accuracy: 0.9060 - val_loss: 0.3502 - val_accuracy: 0.8616
Epoch 4/20
313/313 [==============================] - 4s 12ms/step - loss: 0.2365 - accuracy: 0.9203 - val_loss: 0.3444 - val_accuracy: 0.8626
Epoch 5/20
313/313 [==============================] - 4s 12ms/step - loss: 0.1981 - accuracy: 0.9354 - val_loss: 0.3683 - val_accuracy: 0.8530
Epoch 6/20
313/313 [==============================] - 4s 12ms/step - loss: 0.1796 - accuracy: 0.9412 - val_loss: 0.3647 - val_accuracy: 0.8588
Epoch 7/20
313/313 [==============================] - 4s 12ms/step - loss: 0.1592 - accuracy: 0.9488 - val_loss: 0.3714 - val_accuracy: 0.8614

In [15]:
history = model2.fit(
    x_train, y_train,
    epochs=20,
    batch_size=64,
    validation_split=0.2
)

Epoch 1/20
313/313 [==============================] - 1s 4ms/step - loss: 0.6103 - accuracy: 0.7126 - val_loss: 0.4563 - val_accuracy: 0.8306
Epoch 2/20
313/313 [==============================] - 1s 4ms/step - loss: 0.3457 - accuracy: 0.8741 - val_loss: 0.3149 - val_accuracy: 0.8736
Epoch 3/20
313/313 [==============================] - 1s 3ms/step - loss: 0.2481 - accuracy: 0.9067 - val_loss: 0.2877 - val_accuracy: 0.8854
Epoch 4/20
313/313 [==============================] - 1s 3ms/step - loss: 0.2028 - accuracy: 0.9252 - val_loss: 0.2823 - val_accuracy: 0.8854
Epoch 5/20
313/313 [==============================] - 1s 3ms/step - loss: 0.1714 - accuracy: 0.9389 - val_loss: 0.2867 - val_accuracy: 0.8834
Epoch 6/20
313/313 [==============================] - 1s 3ms/step - loss: 0.1482 - accuracy: 0.9484 - val_loss: 0.3000 - val_accuracy: 0.8848
Epoch 7/20
313/313 [==============================] - 1s 3ms/step - loss: 0.1284 - accuracy: 0.9578 - val_loss: 0.3095 - val_accuracy: 0.8810
Epoch 

In [23]:
model.evaluate(x_test, y_test)


782/782 [==============================] - 4s 5ms/step - loss: 0.9926 - accuracy: 0.8398


[0.992565393447876, 0.8398000001907349]

In [28]:
train_data[:1,]

array([[ 1, 14, 22, ...,  0,  0,  0]])

In [29]:
model.layers[0](train_data[:1,])

<tf.Tensor: shape=(1, 2494, 32), dtype=float32, numpy=
array([[[-0.01354495, -0.02960303,  0.03148795, ..., -0.05934387,
         -0.02715466,  0.09537116],
        [-0.01264619, -0.00025692, -0.0015659 , ...,  0.02500811,
         -0.02690599, -0.01206052],
        [-0.0175575 ,  0.00991232,  0.03665647, ...,  0.0276847 ,
          0.00818988, -0.03269248],
        ...,
        [-0.00814269,  0.04004674,  0.08281032, ..., -0.04586101,
         -0.01793603,  0.08525365],
        [-0.00814269,  0.04004674,  0.08281032, ..., -0.04586101,
         -0.01793603,  0.08525365],
        [-0.00814269,  0.04004674,  0.08281032, ..., -0.04586101,
         -0.01793603,  0.08525365]]], dtype=float32)>

In [11]:
target_words = ["good", "great", "wonderful", "fun",
                "bad", "terrible", "boring", "awful"]

In [13]:
ids = [word_index[w] for w in target_words]

embedding_weights = model.layers[0].get_weights()[0]  # (vocab_size, embedding_dim)

vectors = np.array([embedding_weights[i] for i in ids])

NameError: name 'word_index' is not defined